### ISSUE TITLE
[feature-request] Add a default parallel limit

### ISSUE THREAD

**Issue by theodelrieu** [thomhurst/TUnit#1245]
Hello,

The doc states that:

>If a class doesn't have a parallel limit defined, it'll try and eagerly run when the .NET thread pool allows it to do so, so the upper limit is unknown.

I have a lot of tests that all have a 30s timeout inside (i.e. functional tests making HTTP requests). Without setting a custom `ParallelLimiter`, all tests are launched at the same time, making most of them time out after 30s.

I reckon it would make sense to have a default parallel limiter, e.g. the number of available cores.

**Comment by viceroypenguin** [comment]
> e.g. the number of available cores.

Would be incredibly limiting, causing most threads to be idle if there is a lot of `async` code. Also, I'd imagine it's not common for a repo for "all [tests to] have a 30s timeout inside". My recommendation would be to use the documented limiter for your case specifically, since that's why it exists.

**Comment by thomhurst** [comment]
This is easy enough to do yourself.

Add a file like this to your assembly:

`TUnitOptions.cs`
```csharp
using TUnit.Core.Helpers;

[assembly: ParallelLimiter<DefaultParallelLimit>]
```
