### ISSUE TITLE
[feedback] BeforeEvery has a confusing name

### ISSUE THREAD

**Issue by theodelrieu** [thomhurst/TUnit#1250]
Hello,

I had to browse the code to figure that `BeforeEvery` was run once before all tests, while `Before` is run before each test.
I thought `BeforeEvery` and `BeforeEach` were the same thing.
A native-speaking colleague of mine was also confused, which is why I'm opening this issue. 

I'd suggest renaming `BeforeEvery` to `BeforeAll`, and `Before` to `BeforeEach`. I've seen these names a lot in many frameworks, they seem clearer to me.

Wdyt?

**Comment by thomhurst** [comment]
BeforeAll(Test) would imply to me that it would run once before all tests. But it would run before every test. I think before all would cause more confusion.

**Comment by theodelrieu** [comment]
But isn't that what BeforeEvery does already? Running once before all tests?

**Comment by thomhurst** [comment]
No it runs before every test, hence the name. It's a static hook so it's not tied to the class it's defined in.

Before(Test) - runs before each test in the class it's defined in
BeforeEvery(Test) - runs before every test. Static so not tied to one class type.

**Comment by thomhurst** [comment]
> But isn't that what BeforeEvery does already? Running once before all tests?

If you want to run once before all tests, do Before(TestSession)

**Comment by theodelrieu** [comment]
>Before(Test) - runs **before each** test in the class it's defined in
>BeforeEvery(Test) - runs **before every** test. Static so not tied to one class type.

It might be because I'm not a native speaker, but to me before each/before every mean the exact same thing.
IIUC, the only difference between those two is that one is static and the other isn't, correct?

If that's the case, shouldn't this nuance be reflected in the name directly to avoid confusion?

**Comment by thomhurst** [comment]
```csharp
public class Tests1
{
    [Before(Test)]
    public void Setup()
    {
        // This only affects `Tests1` class because it's just using `[Before]`
    }
}

public class Tests2
{
    [Before(Test)]
    public void Setup()
    {
        // This only affects `Tests2` class because it's just using `[Before]`
    }
}

public class Tests3
{
    [BeforeEvery(Test)]
    public static void Setup(TestContext context)
    {
        // This affects `Tests1` & `Tests2` and any other test class defined because it's using `[BeforeEvery]`.
        // It should probably actually be in its own file to be easy to find, like `GlobalHooks.cs`
    }
}
```

**Comment by ShawnTheBeachy** [comment]
My two cents is that the static vs. not-static requirements make the difference clear. If `BeforeEvery(Test)` could be an instance method *and* `Before(Test)` could be an instance method, I think it would be confusing. But since `BeforeEvery(Test)` *must* be static, IMO it's clear that it's going to run before every test in the *session*. And since `Before(Test)` must *not* be static, IMO it's clear that it's going to run before each test in the *instance*.

Since, IMO, the `static` is what makes the difference clear, I do think it could make sense to just have `Before(Test)` and allow it to be used on either an instance method or a static method. And then the behavior would be defined by whether the method is static or not. But I'm not sure if that's even possible with C# attributes...

**Comment by Juarrow** [comment]
A few more cents:

I agree with @ShawnTheBeachy in that `static` makes it more clear...

BUT:

I also agree with the @theodelrieu , because I would read it like a sentence: 

> Before every test, do the following. 

It's definetly feels different from

> Once before all of the tests, do the following

Having to think about `static` and infer by oneself or reason about the intricacies of interpreting vocabulary seems unnecessary complex. (A weak argument - I know, because how would we communicate without language rules. But as a non-native myself, I fall for it too - especially when just scanning text.)

If possible, keep it simple. In doubt give up that the term has to start with `before` and attach one or two more words to make it a little clearer.


Maybe it would be enough in the documentation of `BeforeEvery` to have the explanation be self-contained and not refer to other points in the list (e.g. "as above").


Hope it helps.

**Comment by thomhurst** [comment]
> because I would read it like a sentence:
Before every test, do the following.

Which is exactly what it does? The Every part literally means Every test. Im not sure why it's unclear 😅

**Comment by Juarrow** [comment]
I find the first example of https://dictionary.cambridge.org/grammar/british-grammar/all-or-every good.

Some other results indicate that the difference between each and every is in the group size (2 vs 3 or more), yet still targeting the individuals.
To me it just shows that English can be hard to get right for non-natives in cases.

I'd still suggest to rewrite description for BeforeEvery in the documentation from a perspective of an outsider/without leaning on the description of the other functions.

**Comment by thomhurst** [comment]
Updated docs here:

https://thomhurst.github.io/TUnit/docs/tutorial-extras/setup
