### ISSUE TITLE
Inherits Tests Does Not Pick Up Tests In Another Project

### ISSUE THREAD

**Issue by jacob7395** [thomhurst/TUnit#1324]
Hey, inheriting test from another project doesn't work. I have created this [branch ](https://github.com/jacob7395/TUnit-fork/tree/inherited-test-issue) with a new project (`TUnit.Inherits.Tests`) that tried to inherit a test from (`TUnit.Core.SourceGenerator.Tests`). Hopefully this offers some help :)

When running the project, it says the `Inconclusive: Test has not run` with the following log file;

[2024-12-01-09-09-48-321___f5685b5c-edce-48fb-88b8-23e06b14a9c0.log](https://github.com/user-attachments/files/17968348/2024-12-01-09-09-48-321___f5685b5c-edce-48fb-88b8-23e06b14a9c0.log)

**Comment by thomhurst** [comment]
Hey @jacob7395 - TUnit.Core.SourceGenerator.Tests is actually using NUnit to run the tests at the moment.

![image](https://github.com/user-attachments/assets/fdf4df01-3c7c-44a2-81f5-cd16ac6ff2eb)

That's why. The Test attribute is actually an NUnit one, not a TUnit one 😆 

I'll try and switch everything over to TUnit eventually. I started with NUnit early on before the framework was fully built so I had something to run tests with at the time.

**Comment by jacob7395** [comment]
Ha, that makes sense how do you test a test project. However did originally get the errors when only using TUnit, I have an example solution but it's a bit harder to share a whole solution.

**Comment by thomhurst** [comment]
If you can try and recreate it in a minimal example feel free to send it over

**Comment by jacob7395** [comment]
Okay, here is a drop box link for my example solutions;

https://www.dropbox.com/scl/fo/j19e1o7fok1svsfzy9lc0/ADxKAjdgE8LyXgnNIIPNbDE?rlkey=8b7kh38ppqe9cp4sacrfzjka4&st=2yg0fmo6&dl=0

**Comment by thomhurst** [comment]
@jacob7395 Think I've resolved it. Can you retry on the latest version?

**Comment by jacob7395** [comment]
> @jacob7395 Think I've resolved it. Can you retry on the latest version?

Will give it a go this evening.

**Comment by jacob7395** [comment]
That seems to have done it, thanks for the quick fix as always ❤️
