### ISSUE TITLE
Please support FluentAssertions!

### ISSUE THREAD

**Issue by alvipeo** [thomhurst/TUnit#572]
You have a very pretty testing lib here. But PLEASE use FluentAssertions.

**Comment by thomhurst** [comment]
You can bring fluent assertions in yourself as a dependency if you need to. Any reason why you think you can't?

**Comment by thomhurst** [comment]
I have also raised a PR to map FA exceptions to TUnit assertions here: https://github.com/fluentassertions/fluentassertions/pull/2758

**Comment by Xen0byte** [comment]
> You can bring fluent assertions in yourself as a dependency if you need to. Any reason why you think you can't?

Indeed, the assertion library can be completely independent from the test framework, and I should probably note that some people, myself included, do prefer `TUnit.Assertions` over `FluentAssertions`, and I do hope that they keep getting iterated on and not left on the backburner just because `FluentAssertions` exists.

I've said this on reddit and I'll say it here too, I really like how `TUnit.Assertions` start with `Assert` so that you can scan for them quickly in the code (as opposed to the `Should` in `FluentAssertions` which I highly dislike being so inconsistently located) but are also fluent, so `TUnit.Assertions` combines the best of both worlds that `NUnit`'s constraint model and `FluentAssertions` bring.

**Comment by thomhurst** [comment]
My PR has been merged, so my work is done. Just have to wait for the 7.0 release I believe. So going to close this 😄 

(https://github.com/fluentassertions/fluentassertions/pull/2758)

**Comment by NxSoftware** [comment]
This didn't age well 😅

https://github.com/fluentassertions/fluentassertions/pull/2943

**Comment by alvipeo** [comment]
yep. switching to Shouldly

**Comment by thomhurst** [comment]
Haha sorry guys. Feels like a bit of a wasted effort, had no idea this was coming!

**Comment by NxSoftware** [comment]
I don't think anyone did 😅

**Comment by vbreuss** [comment]
Please be aware, that TUnit support is only included in fluentassertions v8, which is no longer under apache license, but a commerical one:
https://github.com/fluentassertions/fluentassertions/pull/2943#issuecomment-2593150194

**Comment by Pinox** [comment]
I see Mudblazor just switched from FluentAssertions to AwesomeAssertions. New fork of FluentAssertions supported by the community.

https://github.com/AwesomeAssertions/AwesomeAssertions

**Comment by alvipeo** [comment]
I actually switched to AwesomeAssertions in my projects. Works like a charm!
